baseURL = "https://www.senergygroup.org"
title = "Senergy Group, LLC"
author = "Aaron Reinke"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "tella"
enableRobotsTXT = true

# Please enable this feature if the site is available in Japanese, Chinese or Korean.
#hasCJKLanguage = true

# If you're using Google Analytics, you can enable this feature.
googleAnalytics = "G-8580J3VSDB"

# Disqus Comment System
#disqusShortname = ""

[params]

  [params.logo]
    main = "img/logo/logo.png"
    alt = "Senergy Group Logo"

  [params.site]
    name = "Senergy Group"

  [params.icon]
    #If you want to use FontAwesome, set this parameter to true.
    fa5 = true

  [params.homepage_meta_tags]
    meta_description = "A data science company."
    meta_og_title = "Senergy Group"
    meta_og_type = "website"
    meta_og_url = "https://senergygroup.org"
    meta_og_image = ""
    meta_og_description = "A real estate company with a specialization in data"
    meta_twitter_card = "summary_large_image"
    meta_twitter_site = "@username"
    meta_twitter_creator = "@username"

[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    url = "/products/"
    weight = 1

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 4

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
      weight = 1

  [[menu.footer]]
    name = "Github"
    url = "https://github.com/SenergyGroup"
      weight = 2

[build]
  writeStats = true
